In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
a=np.array([1,2.2,3]) 

In [6]:
a

array([1. , 2.2, 3. ])

In [7]:
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [8]:
a=np.array([[1,2,3],[4,5,6]]) #2d array
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
#dtype
a=np.array([1,2,3],dtype=float) #converting array into float
print(a)

[1. 2. 3.]


In [10]:
#np.arange
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [11]:
a=np.arange(1,10,2)
print(a)


[1 3 5 7 9]


In [12]:
#np.shape
a=np.arange(1,16).reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
#np.ones and np.zeros
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
a=np.ones((5,5),dtype=int)# converting to integer
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
a=np.zeros((5,5),dtype=float)# converting to float
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#np.random give random nos between 0 and 1
a=np.random.random((1,10))
print(a)

[[0.17466013 0.40524772 0.4174484  0.54812865 0.42088495 0.93657786
  0.27227928 0.07152253 0.82863058 0.2438737 ]]


In [17]:
b=np.random.random((1,5,2))
print(b)

[[[0.57206561 0.03468239]
  [0.46293871 0.84086145]
  [0.7880675  0.50071826]
  [0.53027833 0.53078726]
  [0.29693141 0.97946239]]]


In [18]:
#np.linespace min=10 max val=10 in between same common difference between them

a=np.linspace(-10,10,10,dtype=int)
print(a)

[-10  -8  -6  -4  -2   1   3   5   7  10]


In [19]:
#np.identity identity matrices

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# dtype  
a=np.arange(1,16).reshape(3,5)
print(a.dtype)

int32


In [21]:
# size it tells number of elements in array
a.size

15

In [22]:
#tells no. of rows and column of ndarrayy
a.shape

(3, 5)

In [23]:
#astype converting data type suppose one col is of age which is in float form we have to convert it to int

a=np.arange(1,16).reshape(3,5)
print(a.dtype)
print(a.astype(float))

int32
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


# ARRAY OPERATION

In [24]:
#Scalar Operations
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


In [25]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [27]:
a1-3

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [28]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [30]:
#Vector Operations
#Arithmatic
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [32]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [33]:
a1==a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
a1<15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# ARRAY FUNCTION

In [35]:
a1=np.random.random((3,4))*100
a1=np.round(a1)
print(a1)

[[ 65.  79.  53.  50.]
 [  2.   4. 100.  84.]
 [ 22.  29.  28.  99.]]


In [36]:
# min/max/sum/prod
# 0->col and 1-> row

In [37]:
np.max(a1,axis=0) #col wise max

array([ 65.,  79., 100.,  99.])

In [38]:
np.min(a1,axis=1) # row wise min

array([50.,  2., 22.])

In [39]:
# mean/median/std/var

In [40]:
np.mean(a1)

51.25

In [41]:
np.mean(a1,axis=1)

array([61.75, 47.5 , 44.5 ])

In [42]:
np.std(a1)

33.219284058108975

In [43]:
np.var(a1)

1103.5208333333333

In [44]:
#log and exponents

np.log(a1)

array([[4.17438727, 4.36944785, 3.97029191, 3.91202301],
       [0.69314718, 1.38629436, 4.60517019, 4.4308168 ],
       [3.09104245, 3.36729583, 3.33220451, 4.59511985]])

In [45]:
np.exp(a1) #exponents

array([[1.69488924e+28, 2.03828107e+34, 1.04137594e+23, 5.18470553e+21],
       [7.38905610e+00, 5.45981500e+01, 2.68811714e+43, 3.02507732e+36],
       [3.58491285e+09, 3.93133430e+12, 1.44625706e+12, 9.88903032e+42]])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a2=np.arange(15).reshape(3,5)

In [52]:
a1[1,2]

7

In [54]:
a2=np.arange(15).reshape(3,5)
print(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [55]:
a2[1,2]

7

In [56]:
a2[2,4]

14

In [57]:
#3d array or tenser

In [60]:
a3=np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [61]:
a3[1,0,1]

5

In [62]:
a3[0,0,0]

0

In [63]:
a3[0,1,1]

3

In [73]:
a1=np.arange(10)

In [75]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [77]:
a2=np.arange(15).reshape(3,5)
print(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [78]:
for i in a2:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [ ]:
# np.iditer
# here nditer will iterate every element in array... whatsoever the dimension be


In [79]:

for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [80]:
for i in a3:
    print()

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [81]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
#Stacking joing two arrays vertically or horizontally

In [82]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [85]:
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])